version: '3.8'

services:
  postgres-database:
    image: postgres:14.4-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=default
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5422:5432'

  mongo-express: # UI for managing MongoDB
    image: mongo-express
    restart: unless-stopped
    container_name: mongo-express
    depends_on:
      - mongo-database
    ports:
      - "7071:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_SERVER: mongo-test-database

  mongo-database:
    container_name: mongo-test-database
    image: mongo:6.0.1-focal
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: mongo